In [4]:
import pandas as pd
filtered_15AB = './csv/USAI_Doctor-all_2013-2023_filtered_15AB_107271.csv'

filtered_15AB = pd.read_csv (filtered_15AB)
#ใช้คอลัมน์นี้ --> img_path เป็น primary key
print(filtered_15AB .shape)
filtered_15AB.head(10)

(107271, 40)

/home/yupaporn/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (30) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,originalImage,LiverMass,LiverECHO,BileDuct,Followup,hcode,pid,exam_date,img_name,img_path,...,CASE_code,Folder,LiverECHO_PDF,LiverECHO_FattyLiver,img_path29,img_path_new,GroupAB,AB_range,NumAB,AB_code
0,https://tools.cascap.in.th/US_Images/044870000...,Normal,['PDF 1'],No,No Followup,10671,378,2014-09-19,USAI_d2014-09-19_u012_p00378-h10671_0.jpg,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,...,012_2014-09-19-00378-10671,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,PDF 1,Normal,/media/tohn/HDD/Dataset_USAI10K/DBD/2014-09-19...,/media/tohn/HDD/Dataset_USAI10K_Cropped/USAI_d...,['PDF 1'],AB38,1,AB05
1,https://tools.cascap.in.th/US_Images/044870000...,Normal,['PDF 1'],No,No Followup,10671,378,2014-09-19,USAI_d2014-09-19_u012_p00378-h10671_1.jpg,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,...,012_2014-09-19-00378-10671,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,PDF 1,Normal,/media/tohn/HDD/Dataset_USAI10K/DBD/2014-09-19...,/media/tohn/HDD/Dataset_USAI10K_Cropped/USAI_d...,['PDF 1'],AB38,1,AB05
2,https://tools.cascap.in.th/US_Images/044870000...,Normal,['PDF 1'],No,No Followup,10671,378,2014-09-19,USAI_d2014-09-19_u012_p00378-h10671_2.jpg,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,...,012_2014-09-19-00378-10671,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,PDF 1,Normal,/media/tohn/HDD/Dataset_USAI10K/DBD/2014-09-19...,/media/tohn/HDD/Dataset_USAI10K_Cropped/USAI_d...,['PDF 1'],AB38,1,AB05
3,https://tools.cascap.in.th/US_Images/044870000...,Normal,['PDF 1'],No,No Followup,10671,378,2014-09-19,USAI_d2014-09-19_u012_p00378-h10671_3.jpg,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,...,012_2014-09-19-00378-10671,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,PDF 1,Normal,/media/tohn/HDD/Dataset_USAI10K/DBD/2014-09-19...,/media/tohn/HDD/Dataset_USAI10K_Cropped/USAI_d...,['PDF 1'],AB38,1,AB05
4,https://tools.cascap.in.th/US_Images/044870000...,Normal,['PDF 1'],No,No Followup,10671,378,2014-09-19,USAI_d2014-09-19_u012_p00378-h10671_4.jpg,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,...,012_2014-09-19-00378-10671,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,PDF 1,Normal,/media/tohn/HDD/Dataset_USAI10K/DBD/2014-09-19...,/media/tohn/HDD/Dataset_USAI10K_Cropped/USAI_d...,['PDF 1'],AB38,1,AB05
5,https://tools.cascap.in.th/US_Images/044870000...,Normal,['PDF 1'],No,No Followup,10671,378,2014-09-19,USAI_d2014-09-19_u012_p00378-h10671_5.jpg,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,...,012_2014-09-19-00378-10671,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,PDF 1,Normal,/media/tohn/HDD/Dataset_USAI10K/DBD/2014-09-19...,/media/tohn/HDD/Dataset_USAI10K_Cropped/USAI_d...,['PDF 1'],AB38,1,AB05
6,https://tools.cascap.in.th/US_Images/044870000...,Normal,['PDF 1'],No,No Followup,10671,378,2014-09-19,USAI_d2014-09-19_u012_p00378-h10671_6.jpg,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,...,012_2014-09-19-00378-10671,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,PDF 1,Normal,/media/tohn/HDD/Dataset_USAI10K/DBD/2014-09-19...,/media/tohn/HDD/Dataset_USAI10K_Cropped/USAI_d...,['PDF 1'],AB38,1,AB05
7,https://tools.cascap.in.th/US_Images/044870000...,Normal,['PDF 1'],No,No Followup,10671,378,2014-09-19,USAI_d2014-09-19_u012_p00378-h10671_7.jpg,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,...,012_2014-09-19-00378-10671,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,PDF 1,Normal,/media/tohn/HDD/Dataset_USAI10K/DBD/2014-09-19...,/media/tohn/HDD/Dataset_USAI10K_Cropped/USAI_d...,['PDF 1'],AB38,1,AB05
8,https://tools.cascap.in.th/US_Images/044870000...,Normal,['PDF 1'],No,No Followup,10671,378,2014-09-19,USAI_d2014-09-19_u012_p00378-h10671_8.jpg,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,...,012_2014-09-19-00378-10671,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,PDF 1,Normal,/media/tohn/HDD/Dataset_USAI10K/DBD/2014-09-19...,/media/tohn/HDD/Dataset_USAI10K_Cropped/USAI_d...,['PDF 1'],AB38,1,AB05
9,https://tools.cascap.in.th/US_Images/044870000...,Normal,['PDF 1'],No,No Followup,10671,378,2014-09-19,USAI_d2014-09-19_u012_p00378-h10671_9.jpg,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,...,012_2014-09-19-00378-10671,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,PDF 1,Normal,/media/tohn/HDD/Dataset_USAI10K/DBD/2014-09-19...,/media/tohn/HDD/Dataset_USAI10K_Cropped/USAI_d...,['PDF 1'],AB38,1,AB05

In [8]:
usai10k = './csv/fv_usai10k_all_unlearn_mlt_model.csv'  # version ลบ field test แล้ว 
fv_usai10k_all = pd.read_csv (usai10k)
fv_usai10k_all = fv_usai10k_all.loc[:, ~fv_usai10k_all.columns.str.contains('^Unnamed')]
print(fv_usai10k_all.shape)

#ใช้คอลัมน์นี้ --> path เป็น primary key

(227980, 2053)

In [3]:
fv_usai10k_sample = pd.read_csv(usai10k, nrows=5)
fv_usai10k_sample

,no,name,path,name_crop,path_crop,x1,x2,x3,x4,x5,...,x2039,x2040,x2041,x2042,x2043,x2044,x2045,x2046,x2047,x2048
0,1,USAI_d2023-02-16_u844_p01175-h04302_12.jpg,/media/HDD/Dataset_USAI10K/DBD/2023-02-16/844/...,crop_USAI_d2023-02-16_u844_p01175-h04302_12.jpg,/media/HDD/Dataset_USAI10K/DBD_crop/2023-02-16...,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.014585,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2,USAI_d2023-02-16_u844_p01175-h04302_4.jpg,/media/HDD/Dataset_USAI10K/DBD/2023-02-16/844/...,crop_USAI_d2023-02-16_u844_p01175-h04302_4.jpg,/media/HDD/Dataset_USAI10K/DBD_crop/2023-02-16...,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.080094,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,3,USAI_d2023-02-16_u844_p01175-h04302_83.jpg,/media/HDD/Dataset_USAI10K/DBD/2023-02-16/844/...,crop_USAI_d2023-02-16_u844_p01175-h04302_83.jpg,/media/HDD/Dataset_USAI10K/DBD_crop/2023-02-16...,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.041248,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4,USAI_d2023-02-16_u844_p01175-h04302_54.jpg,/media/HDD/Dataset_USAI10K/DBD/2023-02-16/844/...,crop_USAI_d2023-02-16_u844_p01175-h04302_54.jpg,/media/HDD/Dataset_USAI10K/DBD_crop/2023-02-16...,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.116210,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5,USAI_d2023-02-16_u844_p01175-h04302_0.jpg,/media/HDD/Dataset_USAI10K/DBD/2023-02-16/844/...,crop_USAI_d2023-02-16_u844_p01175-h04302_0.jpg,/media/HDD/Dataset_USAI10K/DBD_crop/2023-02-16...,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.036545,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
fv_usai10k_sample['path'][0]

'/media/HDD/Dataset_USAI10K/DBD/2023-02-16/844/01175-04302/images/USAI_d2023-02-16_u844_p01175-h04302_12.jpg'

In [7]:
filtered_15AB['img_path'][0]

'/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/00378-10671/images/USAI_d2014-09-19_u012_p00378-h10671_0.jpg'

In [9]:
# ===================================================
# JOIN ตาราง filtered_15AB กับ fv_usai10k_all
# อิงตาม filtered_15AB โดยใช้ img_path = path
# ===================================================

# เลือกเฉพาะคอลัมน์ path + x1 ถึง x2048
x_cols = [f'x{i}' for i in range(1, 2049)]
fv_subset = fv_usai10k_all[['path'] + x_cols]

# JOIN โดยใช้ img_path (filtered_15AB) = path (fv_usai10k_all)
merged = filtered_15AB.merge(
    fv_subset,
    left_on='img_path',
    right_on='path',
    how='left'  # อิงตาม filtered_15AB
)

print(f'filtered_15AB shape : {filtered_15AB.shape}')
print(f'merged shape        : {merged.shape}')
print(f'match ได้           : {merged["path"].notna().sum():,} rows')
print(f'ไม่ match           : {merged["path"].isna().sum():,} rows')

filtered_15AB shape : (107271, 40)
merged shape        : (107271, 2089)
match ได้           : 107,202 rows
ไม่ match           : 69 rows

In [10]:
merged

,originalImage,LiverMass,LiverECHO,BileDuct,Followup,hcode,pid,exam_date,img_name,img_path,...,x2039,x2040,x2041,x2042,x2043,x2044,x2045,x2046,x2047,x2048
0,https://tools.cascap.in.th/US_Images/044870000...,Normal,['PDF 1'],No,No Followup,10671,378,2014-09-19,USAI_d2014-09-19_u012_p00378-h10671_0.jpg,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,...,0.0,0.0,0.079746,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,https://tools.cascap.in.th/US_Images/044870000...,Normal,['PDF 1'],No,No Followup,10671,378,2014-09-19,USAI_d2014-09-19_u012_p00378-h10671_1.jpg,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,...,0.0,0.0,0.022049,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,https://tools.cascap.in.th/US_Images/044870000...,Normal,['PDF 1'],No,No Followup,10671,378,2014-09-19,USAI_d2014-09-19_u012_p00378-h10671_2.jpg,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,...,0.0,0.0,0.042638,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,https://tools.cascap.in.th/US_Images/044870000...,Normal,['PDF 1'],No,No Followup,10671,378,2014-09-19,USAI_d2014-09-19_u012_p00378-h10671_3.jpg,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,...,0.0,0.0,0.032791,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,https://tools.cascap.in.th/US_Images/044870000...,Normal,['PDF 1'],No,No Followup,10671,378,2014-09-19,USAI_d2014-09-19_u012_p00378-h10671_4.jpg,/media/HDD/Dataset_USAI10K/DBD/2014-09-19/012/...,...,0.0,0.0,0.047808,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107266,https://tools.cascap.in.th/US_Images/044550021...,Normal,['Moderate fatty liver'],No,1 Year,23529,7812,2023-02-10,USAI_d2023-02-10_u844_p07812-h23529_4.jpg,/media/HDD/Dataset_USAI10K/DBD/2023-02-10/844/...,...,0.0,0.0,0.045912,0.0,0.0,0.0,0.0,0.0,0.0,0.0
107267,https://tools.cascap.in.th/US_Images/044550021...,Normal,['Moderate fatty liver'],No,1 Year,23529,7812,2023-02-10,USAI_d2023-02-10_u844_p07812-h23529_7.jpg,/media/HDD/Dataset_USAI10K/DBD/2023-02-10/844/...,...,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
107268,https://tools.cascap.in.th/US_Images/044550021...,Normal,['Moderate fatty liver'],No,1 Year,23529,7812,2023-02-10,USAI_d2023-02-10_u844_p07812-h23529_8.jpg,/media/HDD/Dataset_USAI10K/DBD/2023-02-10/844/...,...,0.0,0.0,0.017607,0.0,0.0,0.0,0.0,0.0,0.0,0.0
107269,https://tools.cascap.in.th/US_Images/235290782...,Normal,['Mild fatty liver'],No,1 Year,23529,7824,2023-02-10,USAI_d2023-02-10_u844_p07824-h23529_7.jpg,/media/HDD/Dataset_USAI10K/DBD/2023-02-10/844/...,...,0.0,0.0,0.049097,0.0,0.0,0.0,0.0,0.0,0.0,0.0
107270,https://tools.cascap.in.th/US_Images/235290782...,Normal,['Mild fatty liver'],No,1 Year,23529,7824,2023-02-10,USAI_d2023-02-10_u844_p07824-h23529_8.jpg,/media/HDD/Dataset_USAI10K/DBD/2023-02-10/844/...,...,0.0,0.0,0.025567,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
# ===================================================
# กรองเอาแค่แถวที่ match ครบ (ไม่มี NaN ใน x columns)
# ===================================================
merged_clean = merged.dropna(subset=['x1']).copy()

print(f'ก่อนกรอง : {merged.shape[0]:,} rows')
print(f'หลังกรอง : {merged_clean.shape[0]:,} rows')
print(f'หายไป    : {merged.shape[0] - merged_clean.shape[0]:,} rows')

ก่อนกรอง : 107,271 rows
หลังกรอง : 107,202 rows
หายไป    : 69 rows

In [13]:
doctor_map = {
    844:  'พญ.สุภัชซา ดีวังพล',
    465:  'รศ.พญ.ปรารถนา เชาวน์ชื่น',
    401:  'พญ.จิตราภรณ์ วงศ์วิวัฒน์ไชย',
    440:  'พญ.ฐิติมา อนุกูลอนันตชัย',
    8:    'รศ.นพ.ณรงค์ศักดิ์ ขันตีแก้ว (มหาวิทยาลัยขอนแก่น)',
    2219: 'พญ. ลลิตา ทับคำภา',
    2952: 'พญ.ภัสษญา ศรีภา',
    12:  'อ.นิตยา',
    349:  'อ.วัลลภ',
    10:  'อ.ผลิญ',
    465:  'อ.ปรารถนา',
    1816: 'อ.วรินทร',
    844:  'พญ.สุภัชชา',
}

# กรองเฉพาะแพทย์ที่ต้องการ
df_filtered_ = merged_clean[merged_clean['Doctor'].isin(doctor_map.keys())].copy()

# Map ชื่อแพทย์
df_filtered_['doctor_name'] = merged_clean['Doctor'].map(doctor_map)

# สรุปจำนวน
summary = df_filtered_.groupby(['Doctor', 'doctor_name']).size().reset_index(name='count')
summary = summary.sort_values('count', ascending=False)
summary

   Doctor doctor_name  count
0      10      อ.ผลิญ  64242
1      12     อ.นิตยา  23049
4     844  พญ.สุภัชชา  12111
2     349     อ.วัลลภ   3442
3     465   อ.ปรารถนา   3018
5    1816    อ.วรินทร   1340

In [14]:
summary = df_filtered_.groupby('Doctor').agg(
    NumberOfCase = ('CASE_doctor', 'nunique'),  # นับ case ไม่ซ้ำ
    NumberOfImg = ('originalImage', 'count')   # นับภาพทั้งหมด
).reset_index()

summary['%Case'] = (summary['NumberOfCase'] / summary['NumberOfCase'].sum() * 100).round(2)
summary = summary.sort_values('NumberOfCase', ascending=False)
print(summary.to_string(index=False))

 Doctor  NumberOfCase  NumberOfImg  %Case
     10          9388        64242  65.45
     12          2229        23049  15.54
    844          1468        12111  10.23
    465           570         3018   3.97
    349           414         3442   2.89
   1816           274         1340   1.91

In [15]:
merged_clean.to_csv('./csv/USAI_Doctor-all_2013-2023_filtered_15AB_fv_usai10k_all_unlearn_mlt_model_107202.csv', index=False)
print(f'บันทึกไฟล์สำเร็จ: filtered_15AB_fv_usai10k_all_unlearn_mlt_model_107202.csv')
print(f'Shape: {merged_clean.shape}')

บันทึกไฟล์สำเร็จ: filtered_15AB_fv_usai10k_all_unlearn_mlt_model_107202.csv
Shape: (107202, 2089)